# Generated by Django 2.0 on 2019-05-12 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190512_0258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-createdDate']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_createdDate']},
        ),
    ]
